name: smh_flutter_sdk
description: 腾讯云媒资托管_flutter SDK
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  crclib:
  convert:
  connectivity_plus:
  crypto:
  intl:
  package_info_plus: ^4.2.0